import styles from "../styles/Home.module.css";
import Head from "next/head";
import { Button, Toggle } from "../component/atoms";
import { FilterNav, Header } from "../component/molecules";
import FilterProvider from "../Context/FilterProvider/FilterProvider";
import { useTheme } from "../Context/ThemeProvider/ThemeProvider";
import { useEffect, useState } from "react";
import Card from "../component/molecules/Card/Card";

export default function Home() {
  const darkTheme = useTheme();
  const BODY_STYLE = {
    backgroundColor: darkTheme ? "var(--midnight)" : "#F2F2F2",
  };
  return (
    <div style={BODY_STYLE} className={styles.padding}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <FilterProvider>
        <FilterNav />
        <Card />
      </FilterProvider>
      <Button variant="primary" size="medium" margin="mg-r-l">
        Load More
      </Button>
    </div>
  );
}
